[env]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
monitor_speed = 9600
board_build.partitions = default.csv
custom_tinker_project_id = weather_watch

lib_deps =
  symlink://../../packages/tinker-core
  symlink://../../packages/tinker-display-max7219

extra_scripts =
  pre:../../scripts/pio/configure_firmware.py

[env:esp32dev]

[env:wokwi]
build_flags =
  -D WOKWI_SIM=1
