[env]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
monitor_speed = 9600

lib_deps =
  symlink://../../packages/tinker-core
  symlink://../../packages/tinker-display-hub75

extra_scripts =
  pre:scripts/generate_version_header.py
  pre:scripts/embed_setup_html.py

[env:esp32dev]

[env:wokwi]
build_flags =
  -D WOKWI_SIM=1
